#
# Module manifest for module 'SEPPmailAPI'
#
# Generated by: Roman Stadlmair
#
# Generated on: 26.01.2021
#

@{

   # Script module or binary module file associated with this manifest.
   RootModule = '.\SEPPmailAPI.psm1'

   # Version number of this module.
   ModuleVersion = '2.0.0'

   # Supported PSEditions
   CompatiblePSEditions = @('Desktop','Core')

   # ID used to uniquely identify this module
   GUID = 'fe22be24-92f4-4e63-ba8d-5e9f26779d9d'

   # Author of this module
   Author = 'The SEPPmail Dev-Team'

   # Company or vendor of this module
   CompanyName = 'SEPPmail AG'

   # Copyright statement for this module
   Copyright = '(c) SEPPmail AG. All rights reserved.'

   # Description of the functionality provided by this module
   Description = 'Receive and manipulate your SEPPmail Appliance beginning with SEPPmail Version 12.1.0.
   With the REST-API you can retrieve and set information via REST, including the option to mass-generate users.
   This PowerShell module is a wrapper around this API to allow more convenient operation and interaction from the command line.'

   # Minimum version of the PowerShell engine required by this module
   PowerShellVersion = '5.1'

   # Name of the PowerShell host required by this module
   # PowerShellHostName = ''

   # Minimum version of the PowerShell host required by this module
   # PowerShellHostVersion = ''

   # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
   # DotNetFrameworkVersion = ''

   # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
   # ClrVersion = ''

   # Processor architecture (None, X86, Amd64) required by this module
   # ProcessorArchitecture = ''

   # Modules that must be imported into the global environment prior to importing this module
   RequiredModules = @('Microsoft.PowerShell.SecretStore','Microsoft.PowerShell.SecretManagement')
   # RequiredModules = @()

   # Assemblies that must be loaded prior to importing this module
   # RequiredAssemblies = @()

   # Script files (.ps1) that are run in the caller's environment prior to importing this module.
   # ScriptsToProcess = @()

   # Type files (.ps1xml) to be loaded when importing this module
   # TypesToProcess = @()

   # Format files (.ps1xml) to be loaded when importing this module
   # FormatsToProcess = @()

   # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
   NestedModules = @(
           '.\Private\SEPPmailAPIPrivate.ps1'
           )

   # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
   FunctionsToExport = @(
         'Find-SMACustomer'
          'Get-SMACustomer'
          'New-SMACustomer'
          'Set-SMACustomer'
       'Remove-SMACustomer'
       'Export-SMACustomer'
       'Import-SMACustomer'
          'Get-SMAEncInfo'
          'Add-SMACustomerAdmin'
       'Remove-SMACustomerAdmin'
          'Set-SMAConfiguration'
          'Get-SMAConfiguration'
          'New-SMAConfiguration'
       'Remove-SMAConfiguration'
         'Test-SMAConfiguration'
         'Find-SMADisclaimer'
          'Get-SMADisclaimer'
          'New-SMADisclaimer'
          'Set-SMADisclaimer'
       'Remove-SMADisclaimer'
         'Find-SMADisclaimerInclude'
          'New-SMADisclaimerInclude'
       'Remove-SMADisclaimerInclude'
         'Find-SMAGinaUser'
          'New-SMAGinaUser'
          'Set-SMAGinaUser'
       'Remove-SMAGinaUser'
         'Find-SMAGroup'
          'Get-SMAGroup'
          'New-SMAGroup'
          'Set-SMAGroup'
       'Remove-SMAGroup'
          'Add-SMAGroupMember'
       'Remove-SMAGroupMember'
          'Get-SMALicense'
         'Find-SMAManagedDomain'
          'Get-SMAManagedDomain'
          'New-SMAManagedDomain'
          'Set-SMAManagedDomain'
       'Remove-SMAManagedDomain'
         'Find-SMATemplate'
          'Get-SMATemplate'
          'New-SMATemplate'
          'Set-SMATemplate'
       'Remove-SMATemplate'
         'Find-SMATemplateInclude'
          'Get-SMATemplateInclude'
          'New-SMATemplateInclude'
       'Remove-SMATemplateInclude'
          'Get-SMAStatistics'
          'Get-SMAUser'
         'Find-SMAUser'
          'New-SMAUser'
          'Set-SMAUser'
       'Remove-SMAUser'
          'Get-SMAUserKey'
       'Remove-SMAUserKey'
   )

   # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
   CmdletsToExport = @()

   # Variables to export from this module
   VariablesToExport = '*'

   # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
   AliasesToExport = @('*')

   # DSC resources to export from this module
   # DscResourcesToExport = @()

   # List of all modules packaged with this module
   # ModuleList = @()

   # List of all files packaged with this module
   FileList = @(
       '.\SEPPmailAPI.psm1',
       '.\SEPPmailAPI.psd1',
       '.\Readme.MD',
       '.\LICENSE',
       '.\examples\examples.md',
       '.\examples\customers.csv',
       '.\examples\NewUsers.csv',
       '.\examples\RemoveUsers.csv',
       '.\examples\UpdateUsers.csv',
       '.\Private\SEPPmailAPIPrivate.ps1',
       '.\Private\SEPPmailAPIPrivate_Cfg.ps1',
       '.\Public\SEPPmailAPI-Customer.ps1',
       '.\Public\SEPPMailAPI-Disclaimer.ps1',
       '.\Public\SEPPMailAPI-Group.ps1',
       '.\Public\SEPPmailAPI-Info.ps1',
       '.\Public\SEPPmailAPI-ManagedDomain.ps1',
       '.\Public\SEPPMailAPI-ModuleCfg.ps1',
       '.\Public\SEPPMailAPI-Statistics.ps1',
       '.\Public\SEPPMailAPI-Template.ps1',
       '.\Public\SEPPmailAPI-User.ps1',
       '.\Public\SEPPmailAPI-Webmail.ps1'
   )

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
   PrivateData = @{
       PSData = @{
           # Tags applied to this module. These help with module discovery in online galleries.
           Tags = @(
                   'SEPPmail',
                   'REST-API',
                   'PSEdition_Desktop',
                   'PSEdition_Core',
                   'Windows',
                   'Linux'
                   'MacOS'
                   )

           # A URL to the license for this module.
           LicenseUri = 'https://github.com/seppmail/SEPPmailAPI/blob/master/LICENSE'

           # A URL to the main website for this project.
           ProjectUri = 'https://github.com/seppmail/SEPPmailAPI'

           # A URL to an icon representing this module.
           IconUri = 'https://avatars1.githubusercontent.com/u/55975553?s=400&u=ab22c52a439397dca458e58dfcec9f0a9dd347db&v=4'

           # ReleaseNotes of this module
           ReleaseNotes =
@'
260121: Initial release - preparation for SM Release 12.1.0 - User path only

050221: User management stable - working with SM Dev Release 12.1.0

080221: 0.5.3 - Fixed TLS issue on older PS5 (WS2016) machines, cleanup exported commands

110321: 0.8.0 - All v1 CmdLets done, cosmetics and testing starting now

020421: 0.8.1 - Adding Support for Credential based security with Token/secret

070721: 0.9.0 - Adding Support for multiple configs and SecretStore

260721: 0.9.1 - Adding Support for Encryption Information

170921: 0.9.2 - Adding Support for ManagedDomain, MailTemplate, Disclaimer

180921: 0.9.3 - Adding Support for Statistics

270921: 0.9.4 - Adding Support for Webmail (GINA) users

031021: 0.9.5 - Adding Support for Groups

071021: 1.0.0 - First Release compatible with SEPpmail 12.1

091021: 1.0.1 - Signing of psd1 file added

141021: 1.0.5 - Linux/macOS test-smaconfig fixed, securestrig fixed, Module init SEPPmail_ModuleCfg fixed.
'@

        # Prerelease string of this module
        # Prerelease = 'beta5'

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

       } # End of PSData hashtable

   } # End of PrivateData hashtable

   # HelpInfo URI of this module
   HelpInfoURI = 'https://github.com/seppmail/SEPPmailAPI/blob/main/examples/examples.md'

   # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
   # DefaultCommandPrefix = ''
}

# SIG # Begin signature block
# MIIVzAYJKoZIhvcNAQcCoIIVvTCCFbkCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCrA/B5/Ku5wjcc
# B3gFCxIUWae6K2I1cb8WI6wZwqJXj6CCEggwggVvMIIEV6ADAgECAhBI/JO0YFWU
# jTanyYqJ1pQWMA0GCSqGSIb3DQEBDAUAMHsxCzAJBgNVBAYTAkdCMRswGQYDVQQI
# DBJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAOBgNVBAcMB1NhbGZvcmQxGjAYBgNVBAoM
# EUNvbW9kbyBDQSBMaW1pdGVkMSEwHwYDVQQDDBhBQUEgQ2VydGlmaWNhdGUgU2Vy
# dmljZXMwHhcNMjEwNTI1MDAwMDAwWhcNMjgxMjMxMjM1OTU5WjBWMQswCQYDVQQG
# EwJHQjEYMBYGA1UEChMPU2VjdGlnbyBMaW1pdGVkMS0wKwYDVQQDEyRTZWN0aWdv
# IFB1YmxpYyBDb2RlIFNpZ25pbmcgUm9vdCBSNDYwggIiMA0GCSqGSIb3DQEBAQUA
# A4ICDwAwggIKAoICAQCN55QSIgQkdC7/FiMCkoq2rjaFrEfUI5ErPtx94jGgUW+s
# hJHjUoq14pbe0IdjJImK/+8Skzt9u7aKvb0Ffyeba2XTpQxpsbxJOZrxbW6q5KCD
# J9qaDStQ6Utbs7hkNqR+Sj2pcaths3OzPAsM79szV+W+NDfjlxtd/R8SPYIDdub7
# P2bSlDFp+m2zNKzBenjcklDyZMeqLQSrw2rq4C+np9xu1+j/2iGrQL+57g2extme
# me/G3h+pDHazJyCh1rr9gOcB0u/rgimVcI3/uxXP/tEPNqIuTzKQdEZrRzUTdwUz
# T2MuuC3hv2WnBGsY2HH6zAjybYmZELGt2z4s5KoYsMYHAXVn3m3pY2MeNn9pib6q
# RT5uWl+PoVvLnTCGMOgDs0DGDQ84zWeoU4j6uDBl+m/H5x2xg3RpPqzEaDux5mcz
# mrYI4IAFSEDu9oJkRqj1c7AGlfJsZZ+/VVscnFcax3hGfHCqlBuCF6yH6bbJDoEc
# QNYWFyn8XJwYK+pF9e+91WdPKF4F7pBMeufG9ND8+s0+MkYTIDaKBOq3qgdGnA2T
# OglmmVhcKaO5DKYwODzQRjY1fJy67sPV+Qp2+n4FG0DKkjXp1XrRtX8ArqmQqsV/
# AZwQsRb8zG4Y3G9i/qZQp7h7uJ0VP/4gDHXIIloTlRmQAOka1cKG8eOO7F/05QID
# AQABo4IBEjCCAQ4wHwYDVR0jBBgwFoAUoBEKIz6W8Qfs4q8p74Klf9AwpLQwHQYD
# VR0OBBYEFDLrkpr/NZZILyhAQnAgNpFcF4XmMA4GA1UdDwEB/wQEAwIBhjAPBgNV
# HRMBAf8EBTADAQH/MBMGA1UdJQQMMAoGCCsGAQUFBwMDMBsGA1UdIAQUMBIwBgYE
# VR0gADAIBgZngQwBBAEwQwYDVR0fBDwwOjA4oDagNIYyaHR0cDovL2NybC5jb21v
# ZG9jYS5jb20vQUFBQ2VydGlmaWNhdGVTZXJ2aWNlcy5jcmwwNAYIKwYBBQUHAQEE
# KDAmMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5jb21vZG9jYS5jb20wDQYJKoZI
# hvcNAQEMBQADggEBABK/oe+LdJqYRLhpRrWrJAoMpIpnuDqBv0WKfVIHqI0fTiGF
# OaNrXi0ghr8QuK55O1PNtPvYRL4G2VxjZ9RAFodEhnIq1jIV9RKDwvnhXRFAZ/ZC
# J3LFI+ICOBpMIOLbAffNRk8monxmwFE2tokCVMf8WPtsAO7+mKYulaEMUykfb9gZ
# pk+e96wJ6l2CxouvgKe9gUhShDHaMuwV5KZMPWw5c9QLhTkg4IUaaOGnSDip0TYl
# d8GNGRbFiExmfS9jzpjoad+sPKhdnckcW67Y8y90z7h+9teDnRGWYpquRRPaf9xH
# +9/DUp/mBlXpnYzyOmJRvOwkDynUWICE5EV7WtgwggYaMIIEAqADAgECAhBiHW0M
# UgGeO5B5FSCJIRwKMA0GCSqGSIb3DQEBDAUAMFYxCzAJBgNVBAYTAkdCMRgwFgYD
# VQQKEw9TZWN0aWdvIExpbWl0ZWQxLTArBgNVBAMTJFNlY3RpZ28gUHVibGljIENv
# ZGUgU2lnbmluZyBSb290IFI0NjAeFw0yMTAzMjIwMDAwMDBaFw0zNjAzMjEyMzU5
# NTlaMFQxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0ZWQxKzAp
# BgNVBAMTIlNlY3RpZ28gUHVibGljIENvZGUgU2lnbmluZyBDQSBSMzYwggGiMA0G
# CSqGSIb3DQEBAQUAA4IBjwAwggGKAoIBgQCbK51T+jU/jmAGQ2rAz/V/9shTUxjI
# ztNsfvxYB5UXeWUzCxEeAEZGbEN4QMgCsJLZUKhWThj/yPqy0iSZhXkZ6Pg2A2NV
# DgFigOMYzB2OKhdqfWGVoYW3haT29PSTahYkwmMv0b/83nbeECbiMXhSOtbam+/3
# 6F09fy1tsB8je/RV0mIk8XL/tfCK6cPuYHE215wzrK0h1SWHTxPbPuYkRdkP05Zw
# mRmTnAO5/arnY83jeNzhP06ShdnRqtZlV59+8yv+KIhE5ILMqgOZYAENHNX9SJDm
# +qxp4VqpB3MV/h53yl41aHU5pledi9lCBbH9JeIkNFICiVHNkRmq4TpxtwfvjsUe
# dyz8rNyfQJy/aOs5b4s+ac7IH60B+Ja7TVM+EKv1WuTGwcLmoU3FpOFMbmPj8pz4
# 4MPZ1f9+YEQIQty/NQd/2yGgW+ufflcZ/ZE9o1M7a5Jnqf2i2/uMSWymR8r2oQBM
# dlyh2n5HirY4jKnFH/9gRvd+QOfdRrJZb1sCAwEAAaOCAWQwggFgMB8GA1UdIwQY
# MBaAFDLrkpr/NZZILyhAQnAgNpFcF4XmMB0GA1UdDgQWBBQPKssghyi47G9IritU
# pimqF6TNDDAOBgNVHQ8BAf8EBAMCAYYwEgYDVR0TAQH/BAgwBgEB/wIBADATBgNV
# HSUEDDAKBggrBgEFBQcDAzAbBgNVHSAEFDASMAYGBFUdIAAwCAYGZ4EMAQQBMEsG
# A1UdHwREMEIwQKA+oDyGOmh0dHA6Ly9jcmwuc2VjdGlnby5jb20vU2VjdGlnb1B1
# YmxpY0NvZGVTaWduaW5nUm9vdFI0Ni5jcmwwewYIKwYBBQUHAQEEbzBtMEYGCCsG
# AQUFBzAChjpodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3RpZ29QdWJsaWNDb2Rl
# U2lnbmluZ1Jvb3RSNDYucDdjMCMGCCsGAQUFBzABhhdodHRwOi8vb2NzcC5zZWN0
# aWdvLmNvbTANBgkqhkiG9w0BAQwFAAOCAgEABv+C4XdjNm57oRUgmxP/BP6YdURh
# w1aVcdGRP4Wh60BAscjW4HL9hcpkOTz5jUug2oeunbYAowbFC2AKK+cMcXIBD0Zd
# OaWTsyNyBBsMLHqafvIhrCymlaS98+QpoBCyKppP0OcxYEdU0hpsaqBBIZOtBajj
# cw5+w/KeFvPYfLF/ldYpmlG+vd0xqlqd099iChnyIMvY5HexjO2AmtsbpVn0OhNc
# WbWDRF/3sBp6fWXhz7DcML4iTAWS+MVXeNLj1lJziVKEoroGs9Mlizg0bUMbOalO
# hOfCipnx8CaLZeVme5yELg09Jlo8BMe80jO37PU8ejfkP9/uPak7VLwELKxAMcJs
# zkyeiaerlphwoKx1uHRzNyE6bxuSKcutisqmKL5OTunAvtONEoteSiabkPVSZ2z7
# 6mKnzAfZxCl/3dq3dUNw4rg3sTCggkHSRqTqlLMS7gjrhTqBmzu1L90Y1KWN/Y5J
# KdGvspbOrTfOXyXvmPL6E52z1NZJ6ctuMFBQZH3pwWvqURR8AgQdULUvrxjUYbHH
# j95Ejza63zdrEcxWLDX6xWls/GDnVNueKjWUH3fTv1Y8Wdho698YADR7TNx8X8z2
# Bev6SivBBOHY+uqiirZtg0y9ShQoPzmCcn63Syatatvx157YK9hlcPmVoa1oDE5/
# L9Uo2bC5a4CH2RwwggZzMIIE26ADAgECAhAMcJlHeeRMvJV4PjhvyrrbMA0GCSqG
# SIb3DQEBDAUAMFQxCzAJBgNVBAYTAkdCMRgwFgYDVQQKEw9TZWN0aWdvIExpbWl0
# ZWQxKzApBgNVBAMTIlNlY3RpZ28gUHVibGljIENvZGUgU2lnbmluZyBDQSBSMzYw
# HhcNMjMwMzIwMDAwMDAwWhcNMjYwMzE5MjM1OTU5WjBqMQswCQYDVQQGEwJERTEP
# MA0GA1UECAwGQmF5ZXJuMSQwIgYDVQQKDBtTRVBQbWFpbCAtIERldXRzY2hsYW5k
# IEdtYkgxJDAiBgNVBAMMG1NFUFBtYWlsIC0gRGV1dHNjaGxhbmQgR21iSDCCAiIw
# DQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAOapobQkNYCMP+Y33JcGo90Soe9Y
# /WWojr4bKHbLNBzKqZ6cku2uCxhMF1Ln6xuI4ATdZvm4O7GqvplG9nF1ad5t2Lus
# 5SLs45AYnODP4aqPbPU/2NGDRpfnceF+XhKeiYBwoIwrPZ04b8bfTpckj/tvenB9
# P8/9hAjWK97xv7+qsIz4lMMaCuWZgi8RlP6XVxsb+jYrHGA1UdHZEpunEFLaO9Ss
# OPqatPAL2LNGs/JVuGdq9p47GKzn+vl+ANd5zZ/TIP1ifX76vorqZ9l9a5mzi/HG
# vq43v2Cj3jrzIQ7uTbxtiLlPQUqkRzPRtiwTV80JdtRE+M+gTf7bT1CTvG2L3scf
# YKFk7S80M7NydxV/qL+l8blGGageCzJ8svju2Mo4BB+ALWr+gBmCGqrM8YKy/wXR
# tbvdEvBOLsATcHX0maw9xRCDRle2jO+ndYkTKZ92AMH6a/WdDfL0HrAWloWWSg62
# TxmJ/QiX54ILQv2Tlh1Al+pjGHN2evxS8i+XoWcUdHPIOoQd37yjnMjCN593wDzj
# XCEuDABYw9BbvfSp29G/uiDGtjttDXzeMRdVCJFgULV9suBVP7yFh9pK/mVpz+aC
# L2PvqiGYR41xRBKqwrfJEdoluRsqDy6KD985EdXkTvdIFKv0B7MfbcBCiGUBcm1r
# fLAbs8Q2lqvqM4bxAgMBAAGjggGpMIIBpTAfBgNVHSMEGDAWgBQPKssghyi47G9I
# ritUpimqF6TNDDAdBgNVHQ4EFgQUL96+KAGrvUgJnXwdVnA/uy+RlEcwDgYDVR0P
# AQH/BAQDAgeAMAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwSgYD
# VR0gBEMwQTA1BgwrBgEEAbIxAQIBAwIwJTAjBggrBgEFBQcCARYXaHR0cHM6Ly9z
# ZWN0aWdvLmNvbS9DUFMwCAYGZ4EMAQQBMEkGA1UdHwRCMEAwPqA8oDqGOGh0dHA6
# Ly9jcmwuc2VjdGlnby5jb20vU2VjdGlnb1B1YmxpY0NvZGVTaWduaW5nQ0FSMzYu
# Y3JsMHkGCCsGAQUFBwEBBG0wazBEBggrBgEFBQcwAoY4aHR0cDovL2NydC5zZWN0
# aWdvLmNvbS9TZWN0aWdvUHVibGljQ29kZVNpZ25pbmdDQVIzNi5jcnQwIwYIKwYB
# BQUHMAGGF2h0dHA6Ly9vY3NwLnNlY3RpZ28uY29tMB4GA1UdEQQXMBWBE3N1cHBv
# cnRAc2VwcG1haWwuY2gwDQYJKoZIhvcNAQEMBQADggGBAHnWpS4Jw/QiiLQi2EYv
# THCtwKsj7O3G7wAN7wijSJcWF7iCx6AoCuCIgGdWiQuEZcv9pIUrXQ6jOSRHsDNX
# SvIhCK9JakZJSseW/SCb1rvxZ4d0n2jm2SdkWf5j7+W+X4JHeCF9ZOw0ULpe5pFs
# IGTh8bmTtUr3yA11yw4vHfXFwin7WbEoTLVKiL0ZUN0Qk+yBniPPSRRlUZIX8P4e
# iXuw7lh9CMaS3HWRKkK89w//18PjUMxhTZJ6dszN2TAfwu1zxdG/RQqvxXUTTAxU
# JrrCuvowtnDQ55yXMxkkSxWUwLxk76WvXwmohRdsavsGJJ9+yxj5JKOd+HIZ1fZ7
# oi0VhyOqFQAnjNbwR/TqPjRxZKjCNLXSM5YSMZKAhqrJssGLINZ2qDK/CEcVDkBS
# 6Hke4jWMczny8nB8+ATJ84MB7tfSoXE7R0FMs1dinuvjVWIyg6klHigpeEiAaSaG
# 5KF7vk+OlquA+x4ohPuWdtFxobOT2OgHQnK4bJitb9aDazGCAxowggMWAgEBMGgw
# VDELMAkGA1UEBhMCR0IxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDErMCkGA1UE
# AxMiU2VjdGlnbyBQdWJsaWMgQ29kZSBTaWduaW5nIENBIFIzNgIQDHCZR3nkTLyV
# eD44b8q62zANBglghkgBZQMEAgEFAKCBhDAYBgorBgEEAYI3AgEMMQowCKACgACh
# AoAAMBkGCSqGSIb3DQEJAzEMBgorBgEEAYI3AgEEMBwGCisGAQQBgjcCAQsxDjAM
# BgorBgEEAYI3AgEVMC8GCSqGSIb3DQEJBDEiBCBSqjvc7rue2v4JNJqLe0SOrfJO
# UNCEB22MMLnBBpfM0DANBgkqhkiG9w0BAQEFAASCAgAWOIsTFy7XkVydr2h3cbuT
# YDfFTjvwHxY11KNWg4n7GfEv4KMwCaspauydKWWbEQn8XtazJ7uAGtaCSWcwP414
# AzADaeFTxdS+WAq+CN6x9OLKwD+1BJywYWp2RUQL60wLp81YAMqih3CC/jP6OXM7
# Ei+4I9yUwaGTJaJO2uWsi/79teJt/i4FsEmslkZdvELS5uQMsqsUD16VqgJhPNRe
# SUAzCuYqU3pXnYS7r+E+EQMTP8NZAwzQmYwaoX9GICbwrQquEBZcVOQCYSapAiOt
# G4ymCGpyv6H7p/bg922Xqp5fSWnc9UEUkDzX/gF4XanEjRoc0rhSMKC5Lo1WjfRj
# C6bzKoM/qkH2q4B6tAbrFbCyXmObjQypvGmHfCEEakPXvWtc4DU4bCFBdqzyuBuh
# m4yvIhVxlbIyQFXKNvqO4p7kwj5WiaXy1qTYjoVMbmNMc0V6Gls1o/21jjke7siU
# WMjRCqK4pqZEzy1QyPTwkppb6piyPa+EvnK7gFmSBNrukcwtc5amcfTZGEjVSUKj
# ubs4Gqr5ypO8dBCr4vj+nD+U4Pj34yE9PNTHZrqgJaGZU1jOQ7qzl2L25MpIIc44
# qulpCuZgTe0oVUYfYcD3nbbJF1B9UiTPz5rSNWWKaKR78bzKo6koh3JR9ox23uDy
# E6w6pO/hKslXrhy7H6mYGQ==
# SIG # End signature block
